# Autor: Rodrigo - Práctica 2 Sistemas Distribuidos
# Service interno (ClusterIP) para el broker

apiVersion: v1
kind: Service
metadata:
  name: broker-service
spec:
  type: ClusterIP
  selector:
    app: broker
  ports:
  - port: 32002
    targetPort: 32002
    protocol: TCP

