# Autor: Rodrigo - Práctica 2 Sistemas Distribuidos
# Service NodePort para exponer los servers externamente

apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  type: NodePort
  selector:
    app: server
  ports:
  - port: 32001
    targetPort: 32001
    nodePort: 30010
    protocol: TCP

